### ISSUE TITLE
Show keybings on prompt commands 

### ISSUE THREAD

**Issue by AbraaoAlves** [krizzdewizz/vscode-refactorix#2]
I believe it is because package.json not contains [contributes.keybindings](https://code.visualstudio.com/docs/extensionAPI/extension-manifest)

![image](https://cloud.githubusercontent.com/assets/608731/15653005/8c7426f6-2660-11e6-976b-ec402d3af6cc.png)

**Comment by krizzdewizz** [comment]
Hi, thanks for the hint. I was aware of that setting but I didn't want to clutter up the user's key-bindings or maybe even overwrite some. But on the other hand...this is what the contribution point is meant for ;)
I'll look into it for the next version

**Comment by krizzdewizz** [comment]
The keybinding contributions were added in version 0.3.0

**Comment by krizzdewizz** [comment]
close.
